export type CsrfRouteClass = 'SAFE' | 'BROWSER' | 'EDGE';
export type CsrfRoute = readonly [
  method: string,
  path: string,
  classification: CsrfRouteClass,
];

export const CSRF_ROUTE_INVENTORY: readonly CsrfRoute[] = [
  ['GET', '/', 'SAFE'],
  ['GET', '/health', 'SAFE'],
  ['GET', '/api/v1/auth/me', 'SAFE'],
  ['GET', '/api/v1/auth/me/alert-settings', 'SAFE'],
  ['PATCH', '/api/v1/auth/me/alert-settings', 'BROWSER'],
  ['POST', '/api/v1/auth/login', 'BROWSER'],
  ['POST', '/api/v1/auth/register', 'BROWSER'],
  ['POST', '/api/v1/auth/logout', 'BROWSER'],
  ['POST', '/api/v1/facilities', 'BROWSER'],
  ['GET', '/api/v1/alerts', 'SAFE'],
  ['GET', '/api/v1/alerts/:id', 'SAFE'],
  ['POST', '/api/v1/alerts/:id/notes', 'BROWSER'],
  ['PATCH', '/api/v1/alerts/:id/ack', 'BROWSER'],
  ['PATCH', '/api/v1/alerts/:id/resolve', 'BROWSER'],
  ['GET', '/api/v1/alerts/:alertId/snapshot', 'SAFE'],
  ['PUT', '/api/v1/alerts/:alertId/snapshot', 'BROWSER'],
  ['GET', '/api/v1/cameras', 'SAFE'],
  ['GET', '/api/v1/cameras/:id', 'SAFE'],
  ['POST', '/api/v1/cameras', 'BROWSER'],
  ['PATCH', '/api/v1/cameras/:id', 'BROWSER'],
  ['DELETE', '/api/v1/cameras/:id', 'BROWSER'],
  ['GET', '/api/v1/dashboard/stream', 'SAFE'],
  ['POST', '/api/v1/dashboard/receipts/delivery', 'BROWSER'],
  ['POST', '/api/v1/dashboard/receipts/presentation', 'BROWSER'],
  ['POST', '/api/v1/admin/system-test-retention/purge', 'BROWSER'],
  ['GET', '/api/v1/admin/edge-credentials', 'SAFE'],
  ['POST', '/api/v1/admin/edge-credentials', 'BROWSER'],
  ['POST', '/api/v1/admin/edge-credentials/:tokenId/rotate', 'BROWSER'],
  ['POST', '/api/v1/admin/edge-credentials/:tokenId/revoke', 'BROWSER'],
  [
    'POST',
    '/api/v1/admin/edge-operations/:operationId/recover-secret',
    'BROWSER',
  ],
  [
    'POST',
    '/api/v1/admin/edge-installations/:edgeInstallationId/replace',
    'BROWSER',
  ],
  [
    'POST',
    '/api/v1/admin/edge-installations/:edgeInstallationId/validation-runs',
    'BROWSER',
  ],
  [
    'POST',
    '/api/v1/admin/edge-installations/:edgeInstallationId/validation-runs/:validationRunId/close',
    'BROWSER',
  ],
  [
    'GET',
    '/api/v1/admin/edge-installations/:edgeInstallationId/validation-runs/:validationRunId/events',
    'SAFE',
  ],
  [
    'POST',
    '/api/v1/admin/edge-installations/:edgeInstallationId/transfers',
    'BROWSER',
  ],
  ['GET', '/api/v1/events', 'SAFE'],
  ['POST', '/api/v1/events', 'EDGE'],
  ['POST', '/api/v1/events/heartbeat', 'EDGE'],
  ['PUT', '/api/v1/events/:eventId/snapshot', 'EDGE'],
  ['GET', '/api/v1/facilities', 'SAFE'],
  ['GET', '/api/v1/facilities/:id', 'SAFE'],
  ['PATCH', '/api/v1/facilities/:id', 'BROWSER'],
  ['GET', '/api/v1/facilities/:id/edge-status', 'SAFE'],
  ['GET', '/api/v1/floors', 'SAFE'],
  ['POST', '/api/v1/floors', 'BROWSER'],
  ['PATCH', '/api/v1/floors/:floorId', 'BROWSER'],
  ['DELETE', '/api/v1/floors/:floorId', 'BROWSER'],
  ['GET', '/api/v1/alerts/:alertId/media', 'SAFE'],
  ['POST', '/api/v1/alerts/:alertId/media/access', 'BROWSER'],
  ['HEAD', '/api/v1/alerts/:alertId/media/content', 'SAFE'],
  ['GET', '/api/v1/alerts/:alertId/media/content', 'SAFE'],
  ['HEAD', '/api/v1/alerts/:alertId/media/download', 'SAFE'],
  ['GET', '/api/v1/alerts/:alertId/media/download', 'SAFE'],
  ['GET', '/api/v1/events/capabilities', 'SAFE'],
  ['PUT', '/api/v1/events/clips/:clipId', 'EDGE'],
  ['PUT', '/api/v1/events/clips/:clipId/state', 'EDGE'],
  ['GET', '/api/v1/ml-config/:facilityId', 'SAFE'],
  ['PUT', '/api/v1/ml-config/:facilityId/night-window', 'BROWSER'],
  ['GET', '/api/v1/spaces', 'SAFE'],
  ['GET', '/api/v1/spaces/:spaceId', 'SAFE'],
  ['POST', '/api/v1/spaces', 'BROWSER'],
  ['PATCH', '/api/v1/spaces/:spaceId', 'BROWSER'],
  ['DELETE', '/api/v1/spaces/:spaceId', 'BROWSER'],
  ['GET', '/api/v1/users', 'SAFE'],
  ['POST', '/api/v1/users', 'BROWSER'],
  ['PATCH', '/api/v1/users/:id/role', 'BROWSER'],
  ['PUT', '/api/v1/edge/cameras', 'EDGE'],
  ['POST', '/api/v1/edge/enrollments/verify', 'EDGE'],
  ['PUT', '/api/v1/edge/topology-snapshots/:snapshotId', 'EDGE'],
  ['POST', '/api/v1/edge/topology-snapshots/:snapshotId/confirm', 'EDGE'],
] as const;
